/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface User {
  Email: string;
  FirstName: string;
  Id: string;
  LastName: string;
  StripeCustomerId: string;
  Username: string;
}
