/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Workspace {
  Id: number;
  Name: string;
  CompanyName: string;
  SubscriptionStatus: string;
  isActive?: boolean;
  pictures?: number;
  videos?: number;
}
