/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Submission } from '../../models/submission';

export interface SubmissionsControllerFindAll$Params {
}

export function submissionsControllerFindAll(http: HttpClient, rootUrl: string, params?: SubmissionsControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Submission>>> {
  const rb = new RequestBuilder(rootUrl, submissionsControllerFindAll.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Submission>>;
    })
  );
}

submissionsControllerFindAll.PATH = '/api/submissions';
