/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { submissionItemsControllerFindAll } from '../fn/submission-items-controller/submission-items-controller-find-all';
import { SubmissionItemsControllerFindAll$Params } from '../fn/submission-items-controller/submission-items-controller-find-all';
import { submissionItemsControllerFindOne } from '../fn/submission-items-controller/submission-items-controller-find-one';
import { SubmissionItemsControllerFindOne$Params } from '../fn/submission-items-controller/submission-items-controller-find-one';
import { submissionItemsControllerRemove } from '../fn/submission-items-controller/submission-items-controller-remove';
import { SubmissionItemsControllerRemove$Params } from '../fn/submission-items-controller/submission-items-controller-remove';

@Injectable({ providedIn: 'root' })
export class SubmissionItemsControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `submissionItemsControllerFindAll()` */
  static readonly SubmissionItemsControllerFindAllPath = '/api/submission-items';

  /**
   * Get all submission items.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `submissionItemsControllerFindAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  submissionItemsControllerFindAll$Response(params?: SubmissionItemsControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<{
}>>> {
    return submissionItemsControllerFindAll(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all submission items.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `submissionItemsControllerFindAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  submissionItemsControllerFindAll(params?: SubmissionItemsControllerFindAll$Params, context?: HttpContext): Observable<Array<{
}>> {
    return this.submissionItemsControllerFindAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<{
}>>): Array<{
}> => r.body)
    );
  }

  /** Path part for operation `submissionItemsControllerFindOne()` */
  static readonly SubmissionItemsControllerFindOnePath = '/api/submission-items/{id}';

  /**
   * Get a submission item by ID.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `submissionItemsControllerFindOne()` instead.
   *
   * This method doesn't expect any request body.
   */
  submissionItemsControllerFindOne$Response(params: SubmissionItemsControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return submissionItemsControllerFindOne(this.http, this.rootUrl, params, context);
  }

  /**
   * Get a submission item by ID.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `submissionItemsControllerFindOne$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  submissionItemsControllerFindOne(params: SubmissionItemsControllerFindOne$Params, context?: HttpContext): Observable<{
}> {
    return this.submissionItemsControllerFindOne$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `submissionItemsControllerRemove()` */
  static readonly SubmissionItemsControllerRemovePath = '/api/submission-items/{id}';

  /**
   * Delete a submission item by ID.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `submissionItemsControllerRemove()` instead.
   *
   * This method doesn't expect any request body.
   */
  submissionItemsControllerRemove$Response(params: SubmissionItemsControllerRemove$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return submissionItemsControllerRemove(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete a submission item by ID.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `submissionItemsControllerRemove$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  submissionItemsControllerRemove(params: SubmissionItemsControllerRemove$Params, context?: HttpContext): Observable<{
}> {
    return this.submissionItemsControllerRemove$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

}
