/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import {Workspace} from '../models/workspace';
import { workspacesControllerFindAll } from '../fn/workspaces-controller/workspaces-controller-find-all';
import { WorkspacesControllerFindAll$Params } from '../fn/workspaces-controller/workspaces-controller-find-all';
import { workspacesControllerFindOne } from '../fn/workspaces-controller/workspaces-controller-find-one';
import { WorkspacesControllerFindOne$Params } from '../fn/workspaces-controller/workspaces-controller-find-one';
import { workspacesControllerRemove } from '../fn/workspaces-controller/workspaces-controller-remove';
import { WorkspacesControllerRemove$Params } from '../fn/workspaces-controller/workspaces-controller-remove';

@Injectable({ providedIn: 'root' })
export class WorkspacesControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `workspacesControllerFindAll()` */
  static readonly WorkspacesControllerFindAllPath = '/api/workspaces';

  /**
   * Get all workspaces.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `workspacesControllerFindAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  workspacesControllerFindAll$Response(params?: WorkspacesControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Workspace>>> {
    return workspacesControllerFindAll(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all workspaces.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `workspacesControllerFindAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  workspacesControllerFindAll(params?: WorkspacesControllerFindAll$Params, context?: HttpContext): Observable<Array<Workspace>> {
    return this.workspacesControllerFindAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Workspace>>): Array<Workspace> => r.body)
    );
  }

  /** Path part for operation `workspacesControllerFindOne()` */
  static readonly WorkspacesControllerFindOnePath = '/api/workspaces/{id}';

  /**
   * Get a workspace by ID.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `workspacesControllerFindOne()` instead.
   *
   * This method doesn't expect any request body.
   */
  workspacesControllerFindOne$Response(params: WorkspacesControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<Workspace>> {
    return workspacesControllerFindOne(this.http, this.rootUrl, params, context);
  }

  /**
   * Get a workspace by ID.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `workspacesControllerFindOne$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  workspacesControllerFindOne(params: WorkspacesControllerFindOne$Params, context?: HttpContext): Observable<Workspace> {
    return this.workspacesControllerFindOne$Response(params, context).pipe(
      map((r: StrictHttpResponse<Workspace>): Workspace => r.body)
    );
  }

  /** Path part for operation `workspacesControllerRemove()` */
  static readonly WorkspacesControllerRemovePath = '/api/workspaces/{id}';

  /**
   * Delete a workspace by ID.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `workspacesControllerRemove()` instead.
   *
   * This method doesn't expect any request body.
   */
  workspacesControllerRemove$Response(params: WorkspacesControllerRemove$Params, context?: HttpContext): Observable<StrictHttpResponse<Workspace>> {
    return workspacesControllerRemove(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete a workspace by ID.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `workspacesControllerRemove$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  workspacesControllerRemove(params: WorkspacesControllerRemove$Params, context?: HttpContext): Observable<Workspace> {
    return this.workspacesControllerRemove$Response(params, context).pipe(
      map((r: StrictHttpResponse<Workspace>): Workspace => r.body)
    );
  }

}
