/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Workspace } from '../../models/workspace';

export interface WorkspacesControllerFindAll$Params {
}

export function workspacesControllerFindAll(http: HttpClient, rootUrl: string, params?: WorkspacesControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Workspace>>> {
  const rb = new RequestBuilder(rootUrl, workspacesControllerFindAll.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Workspace>>;
    })
  );
}

workspacesControllerFindAll.PATH = '/api/workspaces';
